### PR TITLE
[#617]User defined deserializer always should be used before standard…

### PR DESCRIPTION
**Pull request by api-from-the-ion**
… ones.

Created a correction for #617. I little bit of explanations: the culprit is in the TypeDeserializers#assignableCases. Here, the EnumDeserializer will be created for any Enum type. But here we are missing some objects needed to create a user deserializer. So we have to create it earlier in the call stack, directly in the DeserializationModelCreator#deserializerChainInternal, before the call of DeserializationModelCreator#typeDeserializer. 

This way it would be effective for all classes, not just the enums.

On the other hand, I looked on the SerializationModelCreator. Here one first looks in the cache, then for user defined serializer, then for user defined adapter. And only after that the standard serializer would be created. So now both DeserializationModelCreator and SerializationModelCreator will share the same logic on creation of custom / standard elements.

And I forget an `Signed-off-by: Anton Pinsky <anton.pinsky@ionos.com>` - could I change it?

### CODE REVIEW

**Comment by api-from-the-ion** [comment]
On commit for #616. I've changed both EnumSerializer and EnumDeserializer, of course. Now they build the map in the constructor, and use it. The map is filled according to the PropertyModel#getxxxName. So the annotation value has effect.

In EnumDeserializer I needed a whole jsonbContext to get the models. Because of this, I've changed the TypeDeserializerBuilder to set and get the JsonbContext as parameter. There is still a getter for JsonbConfigProperties, but we can remove it. If we do this, we have to change another three classes which use this getter.

**Comment by Verdent** [comment]
Hello, thank you for your contribution!

Would it be possible to ask to to update also the class copyright years? :-)

**Comment by Verdent** [comment]
As far as I can tell, some of the copyright failures are caused by my mistake some time ago and will fix them. As of the rest, I might kindly ask you to fix them.
```
/home/runner/work/yasson/yasson/src/main/java/org/eclipse/yasson/internal/ReflectionUtils.java: Copyright year is wrong; is 2022, should be 2023
/home/runner/work/yasson/yasson/src/test/java/org/eclipse/yasson/defaultmapping/generics/model/LowerBoundTypeVariableWithCollectionAttributeClass.java: Copyright year is wrong; is 2022, should be 2023
/home/runner/work/yasson/yasson/src/test/java/org/eclipse/yasson/defaultmapping/generics/GenericsTest.java: Copyright year is wrong; is 2022, should be 2023
```
These are the ones I will create PR for tomorrow.

**Comment by Verdent** [comment]
Alright, I fixed the master and everything should be correct now! :-)

It sill look like there might be some copyright years remaining to fix.

**Comment by api-from-the-ion** [comment]
> On commit for #616. ...
> 
> In EnumDeserializer I needed a whole jsonbContext to get the models. Because of this, I've changed the TypeDeserializerBuilder to set and get the JsonbContext as parameter. There is still a getter for JsonbConfigProperties, but we can remove it. If we do this, we have to change another three classes which use this getter.

The other possible change was to move the creation of EnumDeserializer out of the TypeDeserializers chain, direct into the DeserializationModelCreator. Then I wouldn't have to change the TypeDeserializerBuilder. But this looks like a more destructive change for me. Of course, it also could be done.

**Comment by api-from-the-ion** [comment]
**Put every call of JsonbBuilder.create in the tests into try-with-resources.**

There is a discussion about similar things here https://github.com/eclipse-ee4j/yasson/pull/586. I don't know if this should be done or not right now. Anyway, I just did it. It is only in the test code, so there we could close any resource of the created JSON instance and builder.

If there is an exception during auto-closing - I think it should break a test. But it also could be irrelevant for the test, so we could silently catch the exception. This also could be discussed.

File: src/main/java/org/eclipse/yasson/internal/deserializer/types/EnumDeserializer.java [hunk 1]
```diff
@@ -13,21 +13,51 @@
...
+        }
+        return nameToConstantMap;
     }
 
-    @SuppressWarnings("unchecked")
+    @SuppressWarnings({"unchecked", "rawtypes"})
     @Override
     Object deserializeStringValue(String value, DeserializationContextImpl context, Type rType) {
-        return Enum.valueOf((Class<Enum>) rType, value);
+        return nameToConstantMap == null ? Enum.valueOf((Class<Enum>) rType, value) : nameToConstantMap.get(value);
```
Comment (Verdent) [inline src/main/java/org/eclipse/yasson/internal/deserializer/types/EnumDeserializer.java:61]: I like this with the result caching. Maybe just a thought, when can it be null?

File: src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java [hunk 2]
```diff
@@ -12,26 +12,57 @@
...
 
+    private final EnumMap<? extends Enum<?>, String> constantToNameMap;
+
     EnumSerializer(TypeSerializerBuilder serializerBuilder) {
         super(serializerBuilder);
+
+        constantToNameMap = createConstantToNameMap(serializerBuilder);
+    }
+
+    private static <E extends Enum<E>> EnumMap<E, String> createConstantToNameMap(TypeSerializerBuilder serializerBuilder) {
```
Comment (Verdent) [inline src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java:37]: Isn't this the same as in EnumDeserializer? Maybe it could be placed on some common place :-)

File: src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java [hunk 3]
```diff
@@ -12,26 +12,57 @@
...
+                Class<E> enumClazz = (Class<E>) clazz;
+                constantToNameMap = new EnumMap<>(enumClazz);
+                ClassModel classModel = serializerBuilder.getJsonbContext().getMappingContext().getOrCreateClassModel(clazz);
+
+                for (E enumConstant : enumClazz.getEnumConstants()) {
+                    PropertyModel model = classModel.getPropertyModel(enumConstant.name());
+                    constantToNameMap.put(enumConstant, model.getWriteName());
+                }
+            } catch (ClassCastException classCastException) {
+                throw new IllegalArgumentException("EnumSerializer can only be used with Enum types");
```
Comment (Verdent) [inline src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java:53]: This should never happen, if method isEnum is used.

File: src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java [hunk 4]
```diff
@@ -12,26 +12,57 @@
...
+            }
+        }
+        return constantToNameMap;
     }
 
     @Override
     void serializeValue(Enum<?> value, JsonGenerator generator, SerializationContextImpl context) {
-        generator.write(value.name());
+        generator.write(constantToNameMap == null ? value.name() : constantToNameMap.get(value));
```
Comment (Verdent) [inline src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java:61]: the same as wit Deserializer. When this map can be null?

File: src/test/java/org/eclipse/yasson/Jsonbs.java [hunk 5]
```diff
@@ -22,4 +25,32 @@ public class Jsonbs {
 	public static final Jsonb nullableJsonb = JsonbBuilder.create(new JsonbConfig().withNullValues(Boolean.TRUE));
     public static final YassonJsonb yassonJsonb = (YassonJsonb) JsonbBuilder.create();
 	public static final YassonJsonb bindingYassonJsonb = (YassonJsonb) new JsonBindingProvider().create().build();
+
+	private static void testWithJsonb(Supplier<Jsonb> supplier, Consumer<Jsonb> consumer){
```
Comment (Verdent) [inline src/test/java/org/eclipse/yasson/Jsonbs.java:29]: Why have you decided to create these methods? :-)

File: src/test/java/org/eclipse/yasson/adapters/model/NumberAdapter.java [hunk 6]
```diff
@@ -12,9 +12,22 @@
 
 package org.eclipse.yasson.adapters.model;
 
+import org.eclipse.yasson.serializers.model.Counter;
+
 import jakarta.json.bind.adapter.JsonbAdapter;
 
 public class NumberAdapter implements JsonbAdapter<Number, String> {
+
+    private final static Counter counter = new Counter();
```
Comment (Verdent) [inline src/test/java/org/eclipse/yasson/adapters/model/NumberAdapter.java:21]: Since it is a constant, it should be named with capital letters.

File: src/test/java/org/eclipse/yasson/customization/JsonbNillableTest.java [hunk 7]
```diff
@@ -87,6 +85,7 @@ public void testNillableInConfig() {
     
     public static class PrimitiveNullBoolean {
 
+        @SuppressWarnings("deprecation")
```
Comment (Verdent) [inline src/test/java/org/eclipse/yasson/customization/JsonbNillableTest.java:88]: What exactly does this mean on the field?

**Review by Verdent — CHANGES_REQUESTED** [review]
Thank you for doing changes to Yasson :-)

I have a few things to note here:
1. since this will be very likely get merged some time after the New Year, It will need to have updated copyright years for a changed files to 2024.
2. If possible, please list here all the issues it fixes
3. I am usually squashing everything when merging, to do not have 100 new commits, but rather one. Are you fine with that?

**Comment by api-from-the-ion** [comment]
> Thank you for doing changes to Yasson :-)
> 
> I have a few things to note here:

1. Done this, the year is 2024 now
2. Here is the list of the tickets I closed in this PR.
```
#611 YassonParser does not implement JsonParser.currentEvent()
#616 Recognize or honor @JsonbProperty annotation when applied to enumerated types.
#617 @JsonbTypeDeserializer is ignored on Enums in 3.0.3; works in 2.0.4
#625 Polymorphic deserialization fails with a JsonValue property
#626 DocumentationExampleTest: tests for date and number formats not working on installations with a non-English default locale.
#627 Components (adapters, de- serializes) not really cached because of the bug in the ComponentMatcher
#630 YassonParser stream and skip methods breaks parser state and DeserializationContext contract
```
Besides, after fixing the main issue, I've done some refactoring and warning fixing. If you need this, I can add some rough description of them, building some groups. At maximum, I can just assemble the list of all comments in my pushes in this PR, except for some small corrections and forgotten classes. Just tell me how deep and long this list should be

3. If we squash, we would have just everything in one commit, not knowing which change belongs to which ticket or theme. This is probably the reason for the list above, this should be the commit comment? If this is OK for you - then this is also OK for me.

File: src/main/java/org/eclipse/yasson/JsonBindingProvider.java [hunk 8]
```diff
@@ -22,6 +22,9 @@
  */
 public class JsonBindingProvider extends JsonbProvider {
 
+    public JsonBindingProvider() {
+    }
+
```
[the remark this answers is not in the document]
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/JsonBindingProvider.java:27]: As I wrote in commit [comment](https://github.com/api-from-the-ion/yasson/commit/a2966bb1d49f1040e5d294a675122747c211e73b) this is because of JPMS: these are the classes in the root package, which is exported. So I get warnings from the compiler, which suggests adding an explicit constructor. I think the public one is OK, because we should be able to create the instances of these classes outside the packages?

File: src/main/java/org/eclipse/yasson/YassonConfig.java [hunk 9]
```diff
@@ -21,6 +21,9 @@
  * Custom properties for configuring Yasson outside of the specification {@link jakarta.json.bind.JsonbConfig} scope.
  */
 public class YassonConfig extends JsonbConfig {
+
+    public YassonConfig() {
+    }
```
[the remark this answers is not in the document]
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/YassonConfig.java:26]: See comment above.

File: src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java [hunk 10]
```diff
@@ -222,63 +222,66 @@ JsonbCreator createJsonbCreator(Executable executable, JsonbCreator existing, Cl
...
+        @SuppressWarnings("unchecked")
+        final AdapterBinding<?, ?> adapterBinding = jsonbContext.getComponentMatcher().introspectAdapterBinding(adapterClass, null);
 
         if (expectedClass.isPresent() && !(
                 ReflectionUtils.getRawType(adapterBinding.getBindingType()).isAssignableFrom(expectedClass.get()))) {
             throw new JsonbException(Messages.getMessage(MessageKeys.ADAPTER_INCOMPATIBLE,
-                                                         adapterBinding.getBindingType(),
-                                                         expectedClass.get()));
+                    adapterBinding.getBindingType(),
+                    expectedClass.get()));
```
[the remark this answers is not in the document]
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java]: I changed the formatting - they are in the same line now.

File: src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java [hunk 11]
```diff
@@ -222,63 +222,66 @@ JsonbCreator createJsonbCreator(Executable executable, JsonbCreator existing, Cl
...
         }
 
-        return getAdapterBindingFromAnnotation(adapterAnnotation, Optional.ofNullable(clsElement.getElement()));
-    }
-
-    private AdapterBinding getAdapterBindingFromAnnotation(JsonbTypeAdapter adapterAnnotation, Optional<Class<?>> expectedClass) {
+        @SuppressWarnings("rawtypes")
         final Class<? extends JsonbAdapter> adapterClass = adapterAnnotation.value();
-        final AdapterBinding adapterBinding = jsonbContext.getComponentMatcher().introspectAdapterBinding(adapterClass, null);
+        @SuppressWarnings("unchecked")
```
[the remark this answers is not in the document]
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java:238]: The problem with suppression on the method level - you suppress all such things everywhere in the method. So if you put a new one, which you probably wouldn't like to be suppressed and paid attention to it - it also would be automatically suppressed in such case. So I try to put the thing like this directly at the point where it happens, so no other occurrences would be suppressed.

Sometimes I have to change code a little because of this. For example, in case of something would be cast without check directly at return of the method, but one can't put suppress on the return. So I have to extract the result of the cast into the new variable, where I can suppress the unchecked cast warning; and return this variable in the next line.

I think this is a healthy approach.

File: src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java [hunk 12]
```diff
@@ -222,63 +222,66 @@ JsonbCreator createJsonbCreator(Executable executable, JsonbCreator existing, Cl
...
+    private AdapterBinding<?, ?> getAdapterBindingFromAnnotation(JsonbTypeAdapter adapterAnnotation, Optional<Class<?>> expectedClass) {
         if (adapterAnnotation == null) {
             return null;
         }
 
-        return getAdapterBindingFromAnnotation(adapterAnnotation, Optional.ofNullable(clsElement.getElement()));
-    }
-
-    private AdapterBinding getAdapterBindingFromAnnotation(JsonbTypeAdapter adapterAnnotation, Optional<Class<?>> expectedClass) {
+        @SuppressWarnings("rawtypes")
```
[the remark this answers is not in the document]
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/AnnotationIntrospector.java:236]: See comment above.

File: src/main/java/org/eclipse/yasson/internal/JsonBinding.java [hunk 13]
```diff
@@ -51,70 +54,51 @@ public class JsonBinding implements YassonJsonb {
         }
     }
 
-    private <T> T deserialize(final Type type, final JsonParser parser, final DeserializationContextImpl unmarshaller) {
-        return unmarshaller.deserialize(type, parser);
+    private <T> T deserialize(final Type type, final Supplier<JsonParser> parserSupplier) {
```
[the remark this answers is not in the document]
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/JsonBinding.java:57]: You are right; I changed it this way.

File: src/main/java/org/eclipse/yasson/internal/components/BeanManagerInstanceCreator.java [hunk 14]
```diff
@@ -61,18 +61,19 @@ public BeanManagerInstanceCreator(Object beanManager) {
      * @return New instance of bean class with injected content.
      */
     @Override
-    @SuppressWarnings("unchecked")
     public <T> T getOrCreateComponent(Class<T> componentClass) {
-        return (T) injectionTargets.computeIfAbsent(componentClass, clazz -> {
+        @SuppressWarnings("unchecked")
```
[the remark this answers is not in the document]
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/components/BeanManagerInstanceCreator.java:65]: I wrote about these suppressions above already.

File: src/main/java/org/eclipse/yasson/internal/deserializer/types/EnumDeserializer.java (hunk 1 above)
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/deserializer/types/EnumDeserializer.java:61]: Yes, caching makes this faster and this map shouldn't be big and take a long time for creation because enums are normally not so long.

As about the null check: right now, the de- or serializer constructor is called only once with the check if the class is an enum. But in the constructor itself it just a class, so we don't know is this an enum class or not. I wrote a code to prevent the NPE in case the class isn't an enum class somehow. So this why the cache map could be null.

In such case, we would have an CCE in this line, even if I prevent a NPE above. The only scenario where this wouldn't happen is when we have another type here than the class we have in a builder in method above. Which is just another kind of error constellation.

So if you think it is OK to have some exception here - I could do this. I just semi-automatically wrote a secure code with fallback to the old logic in some edge case.

File: src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java (hunk 2 above)
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java:37]: I nearly agree with you, but there are two differences. First, we have a map String to Enum in one case and vice verse in another. And second: in one case we need a read name from the model and a write name in another. The rest dealing with enum is just the same.

So I can extract this and put in some common place with two parameters describing these differences. Or just one parameter for the name, and then just reverse the result map in one case or another.

The other question is: where is this common place? Because I see no common or util package here. I just had this refactoring today in the Enum tests. There I have the same code in adapter and de- and serializer. So I extracted the code from the adapter and use it then directly from de- and serializer. I left the common code in the adapter package and use it in the serializer, but I think it is OK to have this kind of import in the tests.

File: src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java (hunk 3 above)
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java:53]: The CCE could happen here not because I cast the class to the enum class, but to some definite enum class E in line 43. Otherwise, I wouldn't have typed constants in the loop. If you think that this wouldn't happen or cause the exception - I can remove the try-catch block. Or if you think that it's OK to have here a CCE been thrown and not IAE.

File: src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java (hunk 4 above)
Comment (api-from-the-ion) [reply src/main/java/org/eclipse/yasson/internal/serializer/types/EnumSerializer.java:61]: I already answered this above.

File: src/test/java/org/eclipse/yasson/Jsonbs.java (hunk 5 above)
Comment (api-from-the-ion) [reply src/test/java/org/eclipse/yasson/Jsonbs.java:29]: In the tests, one always need a Jsonb object to test it. So there are these repeating parts in the test which creates this object one way or another. Sometimes it is in the try-with-resources block, sometimes one forgot about this.

So I extracted these repeating parts into the methods. These methods are the fixtures for the test. The test gets the Jsonb over the consumer and only have to implement the test logic itself in the consumer. No need to write this boilerplate code over and over again, with some unneeded combinations.

I choose to place these methods into this class because this class already has some common constants and methods which used all over the test code. If you think we need another class just for these static methods - I can do it.

File: src/test/java/org/eclipse/yasson/customization/JsonbNillableTest.java (hunk 7 above)
Comment (api-from-the-ion) [reply src/test/java/org/eclipse/yasson/customization/JsonbNillableTest.java:88]: We are using the deprecated parameter (nillable) on the annotation (@JsonbProperty) here. Therefore, I have a suppressor on the field. I think this is an old test from the times when this parameter wasn't deprecated. So suppression is ok right now; this test would be removed as soon as the parameter would be also removed and wouldn't be just deprecated.

**Comment by api-from-the-ion** [comment]
I found a missing case in ReflectionUtils#getOptionalRawType (WildcardType). I closed this and wrote the test. Furthermore, I don't think that we need an extra ticket for this bug - there was an exception in this case.
